apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus
  namespace: kindops
spec:
  interval: 5m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: kindops
spec:
  releaseName: prometheus
  targetNamespace: prometheus
  interval: 1m
  chart:
    spec:
      chart: prometheus
      version: 15.18.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: kindops
  install:
    createNamespace: true
  values:
    server:
      global:
        scrape_interval: 8s
        scrape_timeout: 4s
      ingress:
        enabled: true
        hosts:
        - prometheus.127.0.0.1.nip.io
      extraFlags:
      - web.enable-lifecycle
      - enable-feature=exemplar-storage
