apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tempo
  namespace: kindops
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: kindops
spec:
  releaseName: tempo
  targetNamespace: tempo
  interval: 1m
  chart:
    spec:
      chart: grafana-tempo
      version: 1.4.4
      sourceRef:
        kind: HelmRepository
        name: tempo
        namespace: kindops
  install:
    createNamespace: true
  values:
    fullnameOverride: tempo
    tempo:
      search:
        enabled: true
      traces:
        jaeger:
          grpc: true
          thriftBinary: true
          thriftCompact: true
          thriftHttp: true
        otlp:
          http: true
          grpc: true
        opencensus: true
        zipkin: true
