apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: tempo
  namespace: kindops
spec:
  interval: 5m
  url: oci://registry-1.docker.io/bitnamicharts/grafana-tempo
  ref:
    semver: "3.8.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: kindops
spec:
  releaseName: tempo
  targetNamespace: tempo
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: tempo
    namespace: kindops
  install:
    createNamespace: true
  values:
    fullnameOverride: tempo
    tempo:
      search:
        enabled: true
      traces:
        jaeger:
          grpc: true
          thriftBinary: true
          thriftCompact: true
          thriftHttp: true
        otlp:
          http: true
          grpc: true
        opencensus: true
        zipkin: true
