apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: loki
  namespace: kindops
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: kindops
spec:
  releaseName: loki
  targetNamespace: loki
  interval: 1m
  chart:
    spec:
      chart: grafana-loki
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: kindops
  values:
    fullnameOverride: loki
---
apiVersion: v1
kind: Namespace
metadata:
  name: loki
