apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: promtail
  namespace: kindops
spec:
  interval: 5m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: kindops
spec:
  releaseName: promtail
  targetNamespace: promtail
  interval: 1m
  chart:
    spec:
      chart: promtail
      version: 6.6.2
      sourceRef:
        kind: HelmRepository
        name: promtail
        namespace: kindops
  install:
    createNamespace: true
  values:
    config:
      clients:
      - url: http://loki-distributor.loki.svc.cluster.local:3100/loki/api/v1/push
