apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/wavefrontHQ/wavefront-operator-for-kubernetes/v2.0.3/deploy/kubernetes/wavefront-operator.yaml
