apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/knative-sandbox/net-contour/knative-v1.6.0/config/contour/external.yaml
- ingressclass.yaml
patchesStrategicMerge:
- patches.yaml
replicas:
- name: contour
  count: 1
